### ISSUE TITLE
这个怎么用啊？

### ISSUE THREAD

**Issue by roxsky** [int86/damai#3]
没有在Chrome使用javescript的经验啊，可以告知下怎么使用吗？

**Comment by int86** [comment]
在大麦网先登录账号
在firefox下，按f12
复制粘贴此js脚本，修改performid 和priceid两个值
去到相关演唱会页面，运行此脚本即可

**Comment by roxsky** [comment]
用Firefox的F12后，是在调试台里导入JS吗？没找到导入的地方啊。

**Comment by roxsky** [comment]
谢谢，我在console里运行了。
