### ISSUE TITLE
你在网页端有没有遇见或这种情况：系统检测到您没有安装flashplayer，请安装完成后再继续购票！

### ISSUE THREAD

**Issue by acmilank22** [int86/damai#5]
我在Windows上的Chrome和Edge，Mac上的Chorme试了，都提示这个，怎么破：

![1](https://user-images.githubusercontent.com/12584040/38169757-6073adfa-35a5-11e8-81ca-a30c98b3589e.png)

**Comment by int86** [comment]
请试一下下面的方法
https://support.google.com/chrome/answer/6258784?co=GENIE.Platform%3DDesktop&hl=zh-Hans

**Comment by acmilank22** [comment]
好的 谢了
